# Generated by Django 4.2.6 on 2023-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributer',
            name='recommended_projects',
        ),
        migrations.AddField(
            model_name='contributer',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contributer',
            name='participation_tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
