# Generated by Django 4.2.6 on 2023-10-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_goals',
            new_name='participation_tasks',
        ),
    ]
